# Generated by Django 5.1.4 on 2024-12-19 20:11

import blog.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('media', models.FileField(blank=True, null=True, upload_to=blog.functions.media_upload_location, verbose_name='Insert an Image or Video')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('text_field', models.TextField(verbose_name='Text Field')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Published Date')),
            ],
        ),
    ]
